name: PR CI

on:
  push:
    branches:
      - "main"

jobs:
  build_deb_package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: build deb package
        run: ./gradlew package

      - name: Upload deb artifact
        uses: actions/upload-artifact@v3
        with:
          name: deb build
          path: build/release/main/deb/*
          if-no-files-found: ignore

      - name: Add report
        run: echo "deb package was created" >> $GITHUB_STEP_SUMMARY